#MJ3 Headers,
mjr=[
"FileVersion",
"DateTime",
"MachID",
"MachModel",
"PistonArea",
"Operator",
"Job_No",
"Joint_No",
"PipeMaterial",
"FittingType",
"PipeSize",
"BeadIFP",
"SoakIFP",
"FuseIFP",
"CoolIFP",
"DragPSI",
"BeadPSI",
"SoakPSI",
"FusePSI",
"CoolPSI",
"External_Probe",
"Datalogger_Probe",
"Notes",
"Datalogger_No",
"Software",
"Calibration_Date",
"JunkArea",
"GraphMaxPSI",
"GraphMaxTime",
"GraphNumPoints"
]
dl4=[
"FileVersion",
"Software",
"DateTime",
"Operator",
"Job_No",
"Joint_No",
"MachID",
"MachModel",
"PistonArea",
"FusionType",
"FusionStandard",
"PipeMaterial",
"PipeSize",
"PipeAngle",
"BeadIFP",
"SoakIFP",
"FuseIFP",
"CoolIFP",
"BeadPSI",
"SoakPSI",
"FusePSI",
"CoolPSI",
"Heater",
"MinBead",
"SoakTime",
"OpenCloseTime",
"BeadTime",
"FuseCoolTime",
"DragPSI",
"GraphNumPoints",
"GraphMaxTime",
"Notes",
"Computer",
"Datalogger_No",
"Calibration_Date",
"Firmware",
"External_Probe"
]

for header in dl4:
	print "char *%s=\"%s,\";" % (header, header)
for header in dl4:
	print "for(i=0;i<strlen(%s);i++){insertArray(&headerArray,%s[i]);}" % (header,header)
	#print "insertArray(&headerArray,',');"
print "insertArray(&headerArray,'\\0');"